-- ============================================================
-- Migração: canais e vídeos do SQLite → Supabase
-- ============================================================

-- Canais
insert into channels (name, youtube_channel_id) values
  ('Baby Shark Official', 'UCcdwLMPsaU2ezNSJU1nFoBg'),
  ('BabyBus - Kids Songs and Cartoons', 'UCbbl2RHv7pS04wQ37rJmBqg'),
  ('Bluey - Official Channel', 'UCVgTTROhDlNHxY0sxFMaClQ'),
  ('Cocomelon - Nursery Rhymes', 'UCbCmjCuTUZos6Inko4u57BA'),
  ('Kids TV - Nursery Rhymes And Baby Songs', 'UCPWSNs5YQeOWBFi7FBFIx0g'),
  ('Mega Fun Kids Songs & Nursery Rhymes', 'UCsXVk37bltHxD1rDPwtNM8Q'),
  ('Numberblocks', 'UCPlwvN0w4qFSP1FllALB85g'),
  ('PAW Patrol Official & Friends', 'UCsXxXFBnfY7dQjOzZ5i9nLg');

-- Vídeos
insert into videos (youtube_video_id, channel_id, title, description, thumbnail_default, thumbnail_high, published_at)
values
  ('KENB8W3UVxY', (select id from channels where name = 'Baby Shark Official' limit 1), '[🎃NEW] AH! What Happened to my Face? | Baby Shark Halloween Story | Baby Shark Official', 'Let''s sing and dance with Baby Shark!✨   You''re watching "[  NEW] AH! What Happened to my Face?", a super fun Baby Shark ...', 'https://i.ytimg.com/vi/KENB8W3UVxY/default.jpg', 'https://i.ytimg.com/vi/KENB8W3UVxY/hqdefault.jpg', '2024-10-17T22:00:27Z'),
  ('hXJEUB97q9A', (select id from channels where name = 'Baby Shark Official' limit 1), 'Zombie Grandpa Shark Stole Our Face! | +Compilation | Halloween Song & Stories | Baby Shark Official', 'Let''s sing and dance with Baby Shark!✨   You''re watching "Zombie Grandpa Shark Stole Our Face! ", a super fun compilation of ...', 'https://i.ytimg.com/vi/hXJEUB97q9A/default.jpg', 'https://i.ytimg.com/vi/hXJEUB97q9A/hqdefault.jpg', '2024-10-18T22:00:35Z'),
  ('A060m0OCtiY', (select id from channels where name = 'Baby Shark Official' limit 1), '[🧟‍♀️NEW] NO! It''s the Zombie Shark Finger Family! | Baby Shark Halloween | Baby Shark Official', 'Let''s sing and dance with Baby Shark!✨   You''re watching "[  ‍♀️NEW] NO! It''s the Zombie Shark Finger Family!", a super fun ...', 'https://i.ytimg.com/vi/A060m0OCtiY/default.jpg', 'https://i.ytimg.com/vi/A060m0OCtiY/hqdefault.jpg', '2024-10-20T22:00:06Z'),
  ('86OF4Vop0Kg', (select id from channels where name = 'Baby Shark Official' limit 1), 'I''m Not Scared of Anything! A...A GHOST?! #shorts', 'Let''s sing and dance with Baby Shark!✨   You''re watching "I''m Not Scared of Anything! A...A GHOST?! #shorts", a super fun Baby ...', 'https://i.ytimg.com/vi/86OF4Vop0Kg/default.jpg', 'https://i.ytimg.com/vi/86OF4Vop0Kg/hqdefault.jpg', '2024-10-21T11:00:07Z'),
  ('vjydchmx2v0', (select id from channels where name = 'Baby Shark Official' limit 1), 'Baby Shark, What Do You Want to Be? | +Compilation | Hero, Police & Doctor | Baby Shark Official', 'Let''s sing and dance with Baby Shark!✨   You''re watching "Baby Shark, What Do You Want to Be?, a super fun compilation of ...', 'https://i.ytimg.com/vi/vjydchmx2v0/default.jpg', 'https://i.ytimg.com/vi/vjydchmx2v0/hqdefault.jpg', '2024-10-21T22:00:41Z'),
  ('TuMSWp9_gqU', (select id from channels where name = 'BabyBus - Kids Songs and Cartoons' limit 1), 'Baby''s Trapped in the Bus | Fire Truck | Safety Song | Nursery Rhymes & Kids Songs | BabyBus', 'Let''s learn car safety tips from Captain Aaron of the fire truck! Lyrics: It''s getting hotter. So hot. And I keep sweating. So hot. Oh no, I ...', 'https://i.ytimg.com/vi/TuMSWp9_gqU/default.jpg', 'https://i.ytimg.com/vi/TuMSWp9_gqU/hqdefault.jpg', '2024-11-21T10:30:12Z'),
  ('TLjifvCnOfk', (select id from channels where name = 'BabyBus - Kids Songs and Cartoons' limit 1), '🔴LIVE | Brave Police Patrol Team | Police Chase | Police Car | Nursery Rhymes & Kids Songs | BabyBus', 'Enjoy Sheriff Labrador Story: （  ）YouTube: https://www.youtube.com/playlist?list=PLPA49Pz3BAxMQZcPY3tAF9ODTxlJIawOv ...', 'https://i.ytimg.com/vi/TLjifvCnOfk/default_live.jpg', 'https://i.ytimg.com/vi/TLjifvCnOfk/hqdefault_live.jpg', '2024-11-22T00:43:10Z'),
  ('BPyU8MP4SqQ', (select id from channels where name = 'BabyBus - Kids Songs and Cartoons' limit 1), '🔴LIVE | Train Choo Choo Song | Farm Animals | Animals Sounds | Nursery Rhymes & Kids Songs | BabyBus', 'Enjoy watching BabyBus songs and cartoons! 1、Nursery Rhymes & Kids Cartoon (All!!) | Kiki and Miumiu | Baby Shark ...', 'https://i.ytimg.com/vi/BPyU8MP4SqQ/default_live.jpg', 'https://i.ytimg.com/vi/BPyU8MP4SqQ/hqdefault_live.jpg', '2024-11-22T07:20:15Z'),
  ('KDWJPHSyy3o', (select id from channels where name = 'BabyBus - Kids Songs and Cartoons' limit 1), 'Monster Ambulance Song | Cars Rescue | Safety Rules | Nursery Rhymes & Kids Songs | BabyBus', 'Monster Ambulance is saving the day. Keeping everyone safe is her duty. When someone needs help, she''ll be right there!', 'https://i.ytimg.com/vi/KDWJPHSyy3o/default.jpg', 'https://i.ytimg.com/vi/KDWJPHSyy3o/hqdefault.jpg', '2024-11-22T10:30:14Z'),
  ('OwH-vYrc1A4', (select id from channels where name = 'BabyBus - Kids Songs and Cartoons' limit 1), 'Ten Babies in the Hospital | Safety Rules for Kids | Nursery Rhymes & Kids Songs | BabyBus', 'Stay safe when you''re at home. Let''s learn home safety rules with ten little babies! Lyrics: There were ten in the bed And the doctor ...', 'https://i.ytimg.com/vi/OwH-vYrc1A4/default.jpg', 'https://i.ytimg.com/vi/OwH-vYrc1A4/hqdefault.jpg', '2024-11-23T10:30:20Z'),
  ('2pLzlS9xp9Y', (select id from channels where name = 'Bluey - Official Channel' limit 1), 'Brisbane Welcomes Bluey and Bingo Themed CityDogs 💙🧡 | Bluey #ytshorts', 'Bluey and Bingo make a splash as two of Brisbane''s iconic CityCats transform into CityDogs alongside the opening of bluey''s ...', 'https://i.ytimg.com/vi/2pLzlS9xp9Y/default.jpg', 'https://i.ytimg.com/vi/2pLzlS9xp9Y/hqdefault.jpg', '2024-12-06T15:00:06Z'),
  ('HLrm9s3MBK4', (select id from channels where name = 'Bluey - Official Channel' limit 1), 'A Heeler Family Christmas ✨ 💙 🎁 | Festive Bluey Moments and More! | Bluey', 'Get ready for the FULL EPISODE of Christmas Swim and more christmas-themed moments from Bluey and friends!', 'https://i.ytimg.com/vi/HLrm9s3MBK4/default.jpg', 'https://i.ytimg.com/vi/HLrm9s3MBK4/hqdefault.jpg', '2024-12-06T16:00:22Z'),
  ('ibPUVlZpDe4', (select id from channels where name = 'Bluey - Official Channel' limit 1), 'The Grannies Visit MoMA in New York City 🏙️🥫 | Bluey', 'The Grannies have one more can of beans up their sleeve… catch up on their Mischievous adventure to the Museum of Modern ...', 'https://i.ytimg.com/vi/ibPUVlZpDe4/default.jpg', 'https://i.ytimg.com/vi/ibPUVlZpDe4/hqdefault.jpg', '2024-12-07T13:01:00Z'),
  ('D_DSLKHSRPU', (select id from channels where name = 'Bluey - Official Channel' limit 1), 'Bluey Christmas Sand Art Display 🎄🏖️ | Bluey  #ytshorts', 'Beautiful Christmas Holiday sand art created by @SandstormEvents in Townsville, Australia! SUBSCRIBE TO BLUEY AT ...', 'https://i.ytimg.com/vi/D_DSLKHSRPU/default.jpg', 'https://i.ytimg.com/vi/D_DSLKHSRPU/hqdefault.jpg', '2024-12-08T13:00:15Z'),
  ('guq7g9IaFL0', (select id from channels where name = 'Bluey - Official Channel' limit 1), 'Bluey Holiday Cookies 🎄🍪 Stop Motion Title Sequence BTS 🎥 | Bluey', 'Mum, Dad, Bingo and Bluey as you''ve never seen them before! Countdown to Christmas with this a-dough-able version of the ...', 'https://i.ytimg.com/vi/guq7g9IaFL0/default.jpg', 'https://i.ytimg.com/vi/guq7g9IaFL0/hqdefault.jpg', '2024-12-08T13:00:45Z'),
  ('pAHpu7jB9zw', (select id from channels where name = 'Cocomelon - Nursery Rhymes' limit 1), 'Easy CoComelon Crafts! DIY Happy Cody 1-2-3! #shorts #cocomelon', 'It''s time for some tabletop CRAFTS with CoComelon! Can you follow the quick steps and make the a super happy Cody? Let''s do ...', 'https://i.ytimg.com/vi/pAHpu7jB9zw/default.jpg', 'https://i.ytimg.com/vi/pAHpu7jB9zw/hqdefault.jpg', '2024-10-18T07:00:38Z'),
  ('dYjjwgk9shk', (select id from channels where name = 'Cocomelon - Nursery Rhymes' limit 1), '🔴 CoComelon Family LIVE! Nursery Rhymes & Kids Songs | Full Episodes', 'Subscribe for new videos every week! https://www.youtube.com/c/CoComelon?sub_confirmation=1 Music available on all major ...', 'https://i.ytimg.com/vi/dYjjwgk9shk/default_live.jpg', 'https://i.ytimg.com/vi/dYjjwgk9shk/hqdefault_live.jpg', '2024-10-18T15:47:15Z'),
  ('9nOcaUPiU1g', (select id from channels where name = 'Cocomelon - Nursery Rhymes' limit 1), '🔴CoComelon Halloween LIVE 🎃👻 Best Halloween Songs & Nursery Rhymes for Kids', 'Subscribe for new videos every week! https://www.youtube.com/c/CoComelon?sub_confirmation=1 Music available on all major ...', 'https://i.ytimg.com/vi/9nOcaUPiU1g/default_live.jpg', 'https://i.ytimg.com/vi/9nOcaUPiU1g/hqdefault_live.jpg', '2024-10-18T15:51:53Z'),
  ('jqvUwMBPC5c', (select id from channels where name = 'Cocomelon - Nursery Rhymes' limit 1), 'How far can the RAINBOW slinky stretch🔴🔵🟡?! Easy Experiments with Ms. Appleberry!', 'Do you know how far a slinky can stretch?! Let''s play along and learn with Ms. Appleberry! A REAL LIFE teacher!', 'https://i.ytimg.com/vi/jqvUwMBPC5c/default.jpg', 'https://i.ytimg.com/vi/jqvUwMBPC5c/hqdefault.jpg', '2024-10-20T07:00:33Z'),
  ('vzG0NmKhhTs', (select id from channels where name = 'Cocomelon - Nursery Rhymes' limit 1), '5-4-3-2-1 Halloween Countdown Dance! CoComelon + Blippi Challenge! #cocomelon #shorts', 'It''s the HALLOWEEN COUNTDOWN dance challenge from Blippi and all the CoComelon kids are excited to jump in and dance!', 'https://i.ytimg.com/vi/vzG0NmKhhTs/default.jpg', 'https://i.ytimg.com/vi/vzG0NmKhhTs/hqdefault.jpg', '2024-10-21T07:00:39Z'),
  ('qQWkPfz3r9g', (select id from channels where name = 'Kids TV - Nursery Rhymes And Baby Songs' limit 1), 'Apples and Bananas Song #shorts #trending #viral #babysongs #cartoon #kidsvideos', 'Welcome to Kids TV, where the warmth of childhood meets the joy of learning through fun nursery rhymes and toddler songs!', 'https://i.ytimg.com/vi/qQWkPfz3r9g/default.jpg', 'https://i.ytimg.com/vi/qQWkPfz3r9g/hqdefault.jpg', '2024-12-07T08:30:17Z'),
  ('CTxI-fIyCeo', (select id from channels where name = 'Kids TV - Nursery Rhymes And Baby Songs' limit 1), 'Jingle Bells & More Baby Rhymes Ho Ho Ho! Celebrate Christmas with Kids TV', 'Welcome to Kids TV, where the magic of Christmas meets the joy of learning through fun nursery rhymes and toddler songs!', 'https://i.ytimg.com/vi/CTxI-fIyCeo/default.jpg', 'https://i.ytimg.com/vi/CTxI-fIyCeo/hqdefault.jpg', '2024-12-07T12:27:26Z'),
  ('t5wDGNrzpro', (select id from channels where name = 'Kids TV - Nursery Rhymes And Baby Songs' limit 1), 'Kaboochi Dance Song #babysong #kidsmusic #dancesong #trending #shorts #viral #cartoon #kidstv', 'Welcome to Kids TV, where the warmth of childhood meets the joy of learning through fun nursery rhymes and toddler songs!', 'https://i.ytimg.com/vi/t5wDGNrzpro/default.jpg', 'https://i.ytimg.com/vi/t5wDGNrzpro/hqdefault.jpg', '2024-12-08T11:47:57Z'),
  ('AXfeoPJolIE', (select id from channels where name = 'Kids TV - Nursery Rhymes And Baby Songs' limit 1), 'Jingle Bells #trending #viral #popular #shorts #youtubekids #ytshorts #cartoon #merrychristmas #xmas', 'Welcome to Kids TV, where the warmth of childhood meets the joy of learning through fun nursery rhymes and toddler songs!', 'https://i.ytimg.com/vi/AXfeoPJolIE/default.jpg', 'https://i.ytimg.com/vi/AXfeoPJolIE/hqdefault.jpg', '2024-12-09T08:30:02Z'),
  ('hSOqsVdRmeI', (select id from channels where name = 'Kids TV - Nursery Rhymes And Baby Songs' limit 1), 'Kaboochi Dance Song #babysong #kidsmusic #dancesong #trending #shorts #viral #cartoon #kidstv', 'Welcome to Kids TV, where the warmth of childhood meets the joy of learning through fun nursery rhymes and toddler songs!', 'https://i.ytimg.com/vi/hSOqsVdRmeI/default.jpg', 'https://i.ytimg.com/vi/hSOqsVdRmeI/hqdefault.jpg', '2024-12-09T12:22:16Z'),
  ('bo59Tja3VQA', (select id from channels where name = 'Mega Fun Kids Songs & Nursery Rhymes' limit 1), 'ABC - Learn Every Letter | 26 Alphabet Videos from A to Z', 'ABC Learn Every Letter of the Alphabet with this 26 Video Compilation by Mega Fun Kids Songs. Covering all 26 letters from a to ...', 'https://i.ytimg.com/vi/bo59Tja3VQA/default.jpg', 'https://i.ytimg.com/vi/bo59Tja3VQA/hqdefault.jpg', '2024-06-15T10:45:31Z'),
  ('Yto8DYVLLMs', (select id from channels where name = 'Mega Fun Kids Songs & Nursery Rhymes' limit 1), 'Count to 100 | Simple Big Numbers | Learn Counting to 100', 'Count to 100 with this simple numbers and counting video. Counting to 100 has never been so easy and simple. Starting at 1 and ...', 'https://i.ytimg.com/vi/Yto8DYVLLMs/default.jpg', 'https://i.ytimg.com/vi/Yto8DYVLLMs/hqdefault.jpg', '2024-06-30T11:41:34Z'),
  ('gApEcUs6Tro', (select id from channels where name = 'Mega Fun Kids Songs & Nursery Rhymes' limit 1), 'A is for Apple Song | ABC Alphabet for Children', 'A is for Apple Song for Children! Learn the ABC Alphabet this super fun and simple educational nursery rhyme for kids. With fun ...', 'https://i.ytimg.com/vi/gApEcUs6Tro/default.jpg', 'https://i.ytimg.com/vi/gApEcUs6Tro/hqdefault.jpg', '2024-07-20T14:55:10Z'),
  ('QPhLUrjnBVQ', (select id from channels where name = 'Mega Fun Kids Songs & Nursery Rhymes' limit 1), 'Count to 15 with Animals | Simple Counting for Kids', 'Count to 15 with Animals in this super simple and fun video for kids. Learning counting from 1 to 15 has never been so easy.', 'https://i.ytimg.com/vi/QPhLUrjnBVQ/default.jpg', 'https://i.ytimg.com/vi/QPhLUrjnBVQ/hqdefault.jpg', '2024-07-28T15:25:42Z'),
  ('IDZC11v1Yew', (select id from channels where name = 'Mega Fun Kids Songs & Nursery Rhymes' limit 1), 'ABC Phonics Song with THREE Words | ABC Alphabet Songs for Children', 'Phonics Song with THREE Words + A is for Apple Song | ABC Alphabet Songs for Children Learn the English ABC Alphabet with ...', 'https://i.ytimg.com/vi/IDZC11v1Yew/default.jpg', 'https://i.ytimg.com/vi/IDZC11v1Yew/hqdefault.jpg', '2024-09-14T11:41:24Z'),
  ('vaqXy6_VAsg', (select id from channels where name = 'Numberblocks' limit 1), '🌈 Preschool Patterns | Counting for Kids | 12345 - Learn to Count | Numberblocks', 'Explore the world of patterns with the Numberblocks in this preschool-friendly video! Learn to count and recognise patterns ...', 'https://i.ytimg.com/vi/vaqXy6_VAsg/default.jpg', 'https://i.ytimg.com/vi/vaqXy6_VAsg/hqdefault.jpg', '2024-11-29T12:01:14Z'),
  ('-noCcopEnUY', (select id from channels where name = 'Numberblocks' limit 1), 'Top of the Blocks - Numberblock One''s Christmas Show! | Toy Play & Count | @Numberblocks', 'Can you hear those sleigh bells ringing? How about that fire crackling? It''s the sound of the season and Numberblock One is ...', 'https://i.ytimg.com/vi/-noCcopEnUY/default.jpg', 'https://i.ytimg.com/vi/-noCcopEnUY/hqdefault.jpg', '2024-11-30T11:00:02Z'),
  ('AR03c44wXaA', (select id from channels where name = 'Numberblocks' limit 1), 'Build Numberblock Three! 🟡 Cartoon Maths fun for Kids - Part 2 | Learn to Count #shorts', 'Build Numberblock Three, fun activity for Kids! Fun short for kids, learn to count and play attention with the Numberblocks!', 'https://i.ytimg.com/vi/AR03c44wXaA/default.jpg', 'https://i.ytimg.com/vi/AR03c44wXaA/hqdefault.jpg', '2024-12-04T11:00:10Z'),
  ('82-KBBB4pnE', (select id from channels where name = 'Numberblocks' limit 1), 'Meet Ten | Fun Counting 1 to 10! | Part 5 | Counting made Exciting | Numberblocks #shorts', 'Get ready to dive into the world of numbers, from 1 to 10, and learn to count with excitement and joy. This interactive learning ...', 'https://i.ytimg.com/vi/82-KBBB4pnE/default.jpg', 'https://i.ytimg.com/vi/82-KBBB4pnE/hqdefault.jpg', '2024-12-04T12:00:11Z'),
  ('hIZOGF15CHY', (select id from channels where name = 'Numberblocks' limit 1), 'Two Times Table Tap Dancing! 👟 | Times Tables for Kids | Learn to Count | @Numberblocks', 'Get ready to tap dance your way through the two times tables with Numberblock Two! This fun and energetic video helps kids ...', 'https://i.ytimg.com/vi/hIZOGF15CHY/default.jpg', 'https://i.ytimg.com/vi/hIZOGF15CHY/hqdefault.jpg', '2024-12-05T12:01:00Z'),
  ('8Pyhn1IUHCk', (select id from channels where name = 'PAW Patrol Official & Friends' limit 1), 'Kenan Thompson Gets A PupTalk | PAW Patrol', 'When it comes down to it, don''t we all have a walrus on the roof in some way or another? Luckily, Chase and Rubble can come to ...', 'https://i.ytimg.com/vi/8Pyhn1IUHCk/default.jpg', 'https://i.ytimg.com/vi/8Pyhn1IUHCk/hqdefault.jpg', '2024-12-06T16:00:13Z'),
  ('4Op1GVRee84', (select id from channels where name = 'PAW Patrol Official & Friends' limit 1), 'Snow monster! #PAWPatrol #Shorts', 'Check out our PAW Patrol Shorts channel!: https://www.youtube.com/@PAWPatrolOfficialShorts PAW Patrol is now available in ...', 'https://i.ytimg.com/vi/4Op1GVRee84/default.jpg', 'https://i.ytimg.com/vi/4Op1GVRee84/hqdefault.jpg', '2024-12-07T08:00:05Z'),
  ('SAIoC8Y1qrA', (select id from channels where name = 'PAW Patrol Official & Friends' limit 1), 'Chase is on the Case! - PAW Patrol Episode - Cartoons for Kids Compilation', 'When Wild Cat sets off Chase''s cat allergies, Chase heads out to the desert where he gets trapped with the Ruff-Ruff Pack.', 'https://i.ytimg.com/vi/SAIoC8Y1qrA/default.jpg', 'https://i.ytimg.com/vi/SAIoC8Y1qrA/hqdefault.jpg', '2024-12-07T08:00:18Z'),
  ('DKP3s-aDfyU', (select id from channels where name = 'PAW Patrol Official & Friends' limit 1), 'Mighty Pup''s Wish You A Merry Christmas - Skye''s Music Party - PAW Patrol Music Cartoons for Kids', 'Skye, Liberty, Everest, and the rest of the Paw Patrol just can''t wait for Christmas Day because that means Santa''s on his way!', 'https://i.ytimg.com/vi/DKP3s-aDfyU/default.jpg', 'https://i.ytimg.com/vi/DKP3s-aDfyU/hqdefault.jpg', '2024-12-07T13:00:25Z'),
  ('MtRQMCZTbsc', (select id from channels where name = 'PAW Patrol Official & Friends' limit 1), 'Pirate Pretend Play with Arrby - Skye''s Music Party - PAW Patrol Music Cartoons for Kids', 'Arrrh! The puppies play pirate with their pirate puppy pal, Arrby! Skye, Liberty, Everest, and the rest of the Paw Patrol pups dress ...', 'https://i.ytimg.com/vi/MtRQMCZTbsc/default.jpg', 'https://i.ytimg.com/vi/MtRQMCZTbsc/hqdefault.jpg', '2024-12-08T12:00:21Z');
